### ISSUE TITLE
Help - images in code not showing 

### ISSUE THREAD

**Issue by WithLoveCW** [WithLoveCW/GR-Surprise-4729#1]
Hi there, I’m having an issue with my GitHub pages. The web pages I’ve built that were working for months have now in the last day turned blank with the images not showing

**Comment by bartvdbraak** [comment]
I created a pull request with changes to fix your issues, you can see them here:
https://github.com/WithLoveCW/GR-Surprise-4729/pull/2

**Comment by bartvdbraak** [comment]
You can see the latest changes in your new Github Pages deployment:
- https://withlovecw.github.io/GR-Surprise-4729/

**Comment by WithLoveCW** [comment]
Thank you very much this seems to have done the trick you are brilliant 🙌🏼 Will I be able to use this code and copy to other pages that have encountered the same problem?

**Comment by bartvdbraak** [comment]
Yeah, if you copy the `js` directory with the `js/wScratchPad.min.js` file into your other projects and change the `<script>` tag for its import like I did, you should be good! 

You can see the changes I made here:
- https://github.com/WithLoveCW/GR-Surprise-4729/pull/2/files

Also, could you please consider marking my reply as the answer to your issue in the following discussion thread:
https://github.com/orgs/community/discussions/55516#discussioncomment-5910486

Thank you and good luck!

**Comment by WithLoveCW** [comment]
Hi @bartvdbraak please can you help me with this link as you were so great last time I had an issue

I am having trouble with my scratch card. The scratch out works when I use the link for the first time. But when I refresh the internet browser and re scratch it is not working

(this issue is only happening on mobile. I have tried it on iphone safari and iphone Google Chrome)

**Comment by bartvdbraak** [comment]
Hi @WithLoveCW 

I am currently quite busy (switching jobs). I will try to take a look this week when I find some time left over.

**Comment by WithLoveCW** [comment]
Hi @bartvdbraak,

Thanks for your message. Could you please take a look at the issue I'm experiencing or direct me to someone who can help? The problem persists, and despite reviewing the code myself, I'm still unsure of the cause. I'm happy to pay for the problem to be fixed once it’s resolved, so please let me know.

P.S. Hope your job switch went well!

**Comment by bartvdbraak** [comment]
Hi @WithLoveCW 

I am gonna take some time today to see if I can resolve your issue!

Job switch went well :)

**Comment by WithLoveCW** [comment]
Hi @bartvdbraak glad to hear thank you! Did you have any luck with this?

I have just checked and the issue is still persisting on mobile. Once refreshed the scratch card image behind is not showing on MOB

**Comment by WithLoveCW** [comment]
@bartvdbraak any update would be greatly appreciated thank you!

**Comment by bartvdbraak** [comment]
I've been trying to fix the issue. I think the scratchpad javascript library that's used is outdated for some browsers, so I'm looking to replace it with something else.

**Comment by bartvdbraak** [comment]
This is as far as I got for now:

https://bartvdbraak.github.io/GR-Surprise-4729/

It's unfortunately stretching in all directions which doesn't look as good.

**Comment by WithLoveCW** [comment]
Hi @bartvdbraak  Thank you very much! It looks like the link you sent me is working perfectly on mobile browsers now on that link sent above. Could you please let me know exactly what changes you made to resolve the issue? Also, please share your PayPal details so I can send you a small payment as a token of my appreciation for your help. I really appreciate it!

**Comment by WithLoveCW** [comment]
Hey @bartvdbraak  I've noticed a small issue: the top front image on the updated link is blurry, although the back image is clear. Could you help fix this? Thanks!

**Comment by WithLoveCW** [comment]
@bartvdbraak Hey! I've noticed a small issue: the top front image on the updated link is blurry, although the back image is clear. Could you help fix this? Thanks!

**Comment by bartvdbraak** [comment]
Did my newest changes fix that?
Try: https://bartvdbraak.github.io/GR-Surprise-4729/

Here is the pull request:
- https://github.com/WithLoveCW/GR-Surprise-4729/pull/5

You don't have to pay me anything. If you really feel like you need to give something back, consider donating (a small amount) to the [Blender Foundation](https://fund.blender.org), which is where I work, or any other charity 😃.

**Comment by WithLoveCW** [comment]
Thank you so much, @bartvdbraak that fixed the screen issue, really appreciate your support and patience with this 😊 

I have just made a donation to the Blender Foundation - what a great cause! 
<img width="472" alt="Screenshot 2024-07-17 at 17 38 18" src="https://github.com/user-attachments/assets/a814fb42-4aa7-4243-af26-36aa74b6c5fc">

**Comment by bartvdbraak** [comment]
No worries; I'm glad it works well. The donation is greatly appreciated! ❤️
